//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;

namespace Rewrite.RewriteJava.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface J : Rewrite.Core.Tree
{
    /// <summary>
    /// Represents a Java compilation unit (a source file).
    /// <br/>Example:
    /// <code>{@code
    /// package com.example;
    /// public class MyClass {
    /// }
    /// }</code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class CompilationUnit(
    Guid id,
    Space prefix,
    Markers markers,
    string sourcePath,
    FileAttributes? fileAttributes,
    string? charsetName,
    bool charsetBomMarked,
    Checksum? checksum,
    JRightPadded<Package>? packageDeclaration,
    IList<JRightPadded<Import>> imports,
    IList<ClassDeclaration> classes,
    Space eof
    ) : J    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptJava<P>(JavaVisitor<P> v, P p)
        {
            return v.VisitCompilationUnit(this, p);
        }

        public Guid Id { get;  set; } = id;

        public CompilationUnit WithId(Guid newId)
        {
            return newId == Id ? this : new CompilationUnit(newId, Prefix, Markers, SourcePath, FileAttributes, CharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, Eof);
        }
        public Space Prefix { get;  set; } = prefix;

        public CompilationUnit WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new CompilationUnit(Id, newPrefix, Markers, SourcePath, FileAttributes, CharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, Eof);
        }
        public Markers Markers { get;  set; } = markers;

        public CompilationUnit WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new CompilationUnit(Id, Prefix, newMarkers, SourcePath, FileAttributes, CharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, Eof);
        }
        public string SourcePath { get;  set; } = sourcePath;

        public CompilationUnit WithSourcePath(string newSourcePath)
        {
            return newSourcePath == SourcePath ? this : new CompilationUnit(Id, Prefix, Markers, newSourcePath, FileAttributes, CharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, Eof);
        }
        public FileAttributes? FileAttributes { get;  set; } = fileAttributes;

        public CompilationUnit WithFileAttributes(FileAttributes? newFileAttributes)
        {
            return newFileAttributes == FileAttributes ? this : new CompilationUnit(Id, Prefix, Markers, SourcePath, newFileAttributes, CharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, Eof);
        }
        public string? CharsetName { get;  set; } = charsetName;

        public CompilationUnit WithCharsetName(string? newCharsetName)
        {
            return newCharsetName == CharsetName ? this : new CompilationUnit(Id, Prefix, Markers, SourcePath, FileAttributes, newCharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, Eof);
        }
        public bool CharsetBomMarked { get;  set; } = charsetBomMarked;

        public CompilationUnit WithCharsetBomMarked(bool newCharsetBomMarked)
        {
            return newCharsetBomMarked == CharsetBomMarked ? this : new CompilationUnit(Id, Prefix, Markers, SourcePath, FileAttributes, CharsetName, newCharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, Eof);
        }
        public Checksum? Checksum { get;  set; } = checksum;

        public CompilationUnit WithChecksum(Checksum? newChecksum)
        {
            return newChecksum == Checksum ? this : new CompilationUnit(Id, Prefix, Markers, SourcePath, FileAttributes, CharsetName, CharsetBomMarked, newChecksum, _packageDeclaration, _imports, Classes, Eof);
        }
        private JRightPadded<J.Package>? _packageDeclaration = packageDeclaration;
        public J.Package? PackageDeclaration => _packageDeclaration?.Element;

        public CompilationUnit WithPackageDeclaration(J.Package? newPackageDeclaration)
        {
            return Padding.WithPackageDeclaration(JRightPadded<J.Package>.WithElement(_packageDeclaration, newPackageDeclaration));
        }
        private IList<JRightPadded<J.Import>> _imports = imports;
        public IList<J.Import> Imports => _imports.Elements();

        public CompilationUnit WithImports(IList<J.Import> newImports)
        {
            return Padding.WithImports(_imports.WithElements(newImports));
        }
        public IList<J.ClassDeclaration> Classes { get;  set; } = classes;

        public CompilationUnit WithClasses(IList<J.ClassDeclaration> newClasses)
        {
            return newClasses == Classes ? this : new CompilationUnit(Id, Prefix, Markers, SourcePath, FileAttributes, CharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, newClasses, Eof);
        }
        public Space Eof { get;  set; } = eof;

        public CompilationUnit WithEof(Space newEof)
        {
            return newEof == Eof ? this : new CompilationUnit(Id, Prefix, Markers, SourcePath, FileAttributes, CharsetName, CharsetBomMarked, Checksum, _packageDeclaration, _imports, Classes, newEof);
        }
        public sealed record PaddingHelper(J.CompilationUnit T)
        {
            public JRightPadded<J.Package>? PackageDeclaration { get => T._packageDeclaration;  set => T._packageDeclaration = value; }

            public J.CompilationUnit WithPackageDeclaration(JRightPadded<J.Package>? newPackageDeclaration)
            {
                return PackageDeclaration == newPackageDeclaration ? T : new J.CompilationUnit(T.Id, T.Prefix, T.Markers, T.SourcePath, T.FileAttributes, T.CharsetName, T.CharsetBomMarked, T.Checksum, newPackageDeclaration, T._imports, T.Classes, T.Eof);
            }

            public IList<JRightPadded<J.Import>> Imports { get => T._imports;  set => T._imports = value; }

            public J.CompilationUnit WithImports(IList<JRightPadded<J.Import>> newImports)
            {
                return Imports == newImports ? T : new J.CompilationUnit(T.Id, T.Prefix, T.Markers, T.SourcePath, T.FileAttributes, T.CharsetName, T.CharsetBomMarked, T.Checksum, T._packageDeclaration, newImports, T.Classes, T.Eof);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is CompilationUnit && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }

        public ITreeVisitor<Core.Tree, PrintOutputCapture<P>> Printer<P>(Cursor cursor)
        {
            return IPrinterFactory.Current()!.CreatePrinter<P>();
        }
    }
}