//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;

namespace Rewrite.RewriteJava.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface J : Rewrite.Core.Tree
{
    /// <summary>
    /// Represents an intersection type.
    /// <br/>Example:
    /// <code>{@code
    /// Serializable & Closeable
    /// }</code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class IntersectionType(
    Guid id,
    Space prefix,
    Markers markers,
    JContainer<TypeTree> bounds
    ) : J, TypeTree, Expression, Expression<IntersectionType>, TypedTree<IntersectionType>, J<IntersectionType>, TypeTree<IntersectionType>, MutableTree<IntersectionType>
    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptJava<P>(JavaVisitor<P> v, P p)
        {
            return v.VisitIntersectionType(this, p);
        }

        public Guid Id { get;  set; } = id;

        public IntersectionType WithId(Guid newId)
        {
            return newId == Id ? this : new IntersectionType(newId, Prefix, Markers, _bounds);
        }
        public Space Prefix { get;  set; } = prefix;

        public IntersectionType WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new IntersectionType(Id, newPrefix, Markers, _bounds);
        }
        public Markers Markers { get;  set; } = markers;

        public IntersectionType WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new IntersectionType(Id, Prefix, newMarkers, _bounds);
        }
        private JContainer<TypeTree> _bounds = bounds;
        public IList<TypeTree> Bounds => _bounds.GetElements();

        public IntersectionType WithBounds(IList<TypeTree> newBounds)
        {
            return Padding.WithBounds(JContainer<TypeTree>.WithElements(_bounds, newBounds));
        }
        public sealed record PaddingHelper(J.IntersectionType T)
        {
            public JContainer<TypeTree> Bounds { get => T._bounds;  set => T._bounds = value; }

            public J.IntersectionType WithBounds(JContainer<TypeTree> newBounds)
            {
                return Bounds == newBounds ? T : new J.IntersectionType(T.Id, T.Prefix, T.Markers, newBounds);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is IntersectionType && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}