//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;

namespace Rewrite.RewriteJava.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface J : Rewrite.Core.Tree
{
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class NewArray(
    Guid id,
    Space prefix,
    Markers markers,
    TypeTree? typeExpression,
    IList<ArrayDimension> dimensions,
    JContainer<Expression>? initializer,
    JavaType? type
    ) : J, Expression, TypedTree, Expression<NewArray>, TypedTree<NewArray>, J<NewArray>, MutableTree<NewArray>
    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptJava<P>(JavaVisitor<P> v, P p)
        {
            return v.VisitNewArray(this, p);
        }

        public Guid Id { get;  set; } = id;

        public NewArray WithId(Guid newId)
        {
            return newId == Id ? this : new NewArray(newId, Prefix, Markers, TypeExpression, Dimensions, _initializer, Type);
        }
        public Space Prefix { get;  set; } = prefix;

        public NewArray WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new NewArray(Id, newPrefix, Markers, TypeExpression, Dimensions, _initializer, Type);
        }
        public Markers Markers { get;  set; } = markers;

        public NewArray WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new NewArray(Id, Prefix, newMarkers, TypeExpression, Dimensions, _initializer, Type);
        }
        public TypeTree? TypeExpression { get;  set; } = typeExpression;

        public NewArray WithTypeExpression(TypeTree? newTypeExpression)
        {
            return ReferenceEquals(newTypeExpression, TypeExpression) ? this : new NewArray(Id, Prefix, Markers, newTypeExpression, Dimensions, _initializer, Type);
        }
        public IList<J.ArrayDimension> Dimensions { get;  set; } = dimensions;

        public NewArray WithDimensions(IList<J.ArrayDimension> newDimensions)
        {
            return newDimensions == Dimensions ? this : new NewArray(Id, Prefix, Markers, TypeExpression, newDimensions, _initializer, Type);
        }
        private JContainer<Expression>? _initializer = initializer;
        public IList<Expression>? Initializer => _initializer?.GetElements();

        public NewArray WithInitializer(IList<Expression>? newInitializer)
        {
            return Padding.WithInitializer(JContainer<Expression>.WithElementsNullable(_initializer, newInitializer));
        }
        public JavaType? Type { get;  set; } = type;

        public NewArray WithType(JavaType? newType)
        {
            return newType == Type ? this : new NewArray(Id, Prefix, Markers, TypeExpression, Dimensions, _initializer, newType);
        }
        public sealed record PaddingHelper(J.NewArray T)
        {
            public JContainer<Expression>? Initializer { get => T._initializer;  set => T._initializer = value; }

            public J.NewArray WithInitializer(JContainer<Expression>? newInitializer)
            {
                return Initializer == newInitializer ? T : new J.NewArray(T.Id, T.Prefix, T.Markers, T.TypeExpression, T.Dimensions, newInitializer, T.Type);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is NewArray && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}