//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;

namespace Rewrite.RewriteJava.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface J : Rewrite.Core.Tree
{
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public sealed partial class Yield(
    Guid id,
    Space prefix,
    Markers markers,
    bool @implicit,
    Expression value
    ) : J,Statement    {
        public J? AcceptJava<P>(JavaVisitor<P> v, P p)
        {
            return v.VisitYield(this, p);
        }

        public Guid Id { get;  set; } = id;

        public Yield WithId(Guid newId)
        {
            return newId == Id ? this : new Yield(newId, Prefix, Markers, Implicit, Value);
        }
        public Space Prefix { get;  set; } = prefix;

        public Yield WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new Yield(Id, newPrefix, Markers, Implicit, Value);
        }
        public Markers Markers { get;  set; } = markers;

        public Yield WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new Yield(Id, Prefix, newMarkers, Implicit, Value);
        }
        public bool Implicit { get;  set; } = @implicit;

        public Yield WithImplicit(bool newImplicit)
        {
            return newImplicit == Implicit ? this : new Yield(Id, Prefix, Markers, newImplicit, Value);
        }
        public Expression Value { get;  set; } = value;

        public Yield WithValue(Expression newValue)
        {
            return ReferenceEquals(newValue, Value) ? this : new Yield(Id, Prefix, Markers, Implicit, newValue);
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is Yield && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}