//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class AnnotatedStatement(
    Guid id,
    Space prefix,
    Markers markers,
    IList<AttributeList> attributeLists,
    Statement statement
    ) : Cs, Statement
    {
        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitAnnotatedStatement(this, p);
        }

        public Guid Id { get;  set; } = id;

        public AnnotatedStatement WithId(Guid newId)
        {
            return newId == Id ? this : new AnnotatedStatement(newId, Prefix, Markers, AttributeLists, Statement);
        }
        public Space Prefix { get;  set; } = prefix;

        public AnnotatedStatement WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new AnnotatedStatement(Id, newPrefix, Markers, AttributeLists, Statement);
        }
        public Markers Markers { get;  set; } = markers;

        public AnnotatedStatement WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new AnnotatedStatement(Id, Prefix, newMarkers, AttributeLists, Statement);
        }
        public IList<Cs.AttributeList> AttributeLists { get;  set; } = attributeLists;

        public AnnotatedStatement WithAttributeLists(IList<Cs.AttributeList> newAttributeLists)
        {
            return newAttributeLists == AttributeLists ? this : new AnnotatedStatement(Id, Prefix, Markers, newAttributeLists, Statement);
        }
        public Statement Statement { get;  set; } = statement;

        public AnnotatedStatement WithStatement(Statement newStatement)
        {
            return ReferenceEquals(newStatement, Statement) ? this : new AnnotatedStatement(Id, Prefix, Markers, AttributeLists, newStatement);
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is AnnotatedStatement && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}