//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    /// <summary>
    /// Represents a C# LINQ orderby clause that specifies the ordering of results in a query.
    /// <br/>
    /// For example:
    /// <code>
    ///     // Simple orderby with single key
    ///     from p in people
    ///     orderby p.LastName
    ///     select p
    ///     // Multiple orderings
    ///     from p in people
    ///     orderby p.LastName ascending, p.FirstName descending
    ///     select p
    ///     // Orderby with complex key expressions
    ///     from o in orders
    ///     orderby o.Customer.Name, o.Total * 1.08
    ///     select o
    /// </code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class OrderByClause(
    Guid id,
    Space prefix,
    Markers markers,
    IList<JRightPadded<Ordering>> orderings
    ) : Cs, Cs.QueryClause, J<OrderByClause>, MutableTree<OrderByClause>
    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitOrderByClause(this, p);
        }

        public Guid Id { get;  set; } = id;

        public OrderByClause WithId(Guid newId)
        {
            return newId == Id ? this : new OrderByClause(newId, Prefix, Markers, _orderings);
        }
        public Space Prefix { get;  set; } = prefix;

        public OrderByClause WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new OrderByClause(Id, newPrefix, Markers, _orderings);
        }
        public Markers Markers { get;  set; } = markers;

        public OrderByClause WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new OrderByClause(Id, Prefix, newMarkers, _orderings);
        }
        private IList<JRightPadded<Cs.Ordering>> _orderings = orderings;
        public IList<Cs.Ordering> Orderings => _orderings.Elements();

        public OrderByClause WithOrderings(IList<Cs.Ordering> newOrderings)
        {
            return Padding.WithOrderings(_orderings.WithElements(newOrderings));
        }
        public sealed record PaddingHelper(Cs.OrderByClause T)
        {
            public IList<JRightPadded<Cs.Ordering>> Orderings { get => T._orderings;  set => T._orderings = value; }

            public Cs.OrderByClause WithOrderings(IList<JRightPadded<Cs.Ordering>> newOrderings)
            {
                return Orderings == newOrderings ? T : new Cs.OrderByClause(T.Id, T.Prefix, T.Markers, newOrderings);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is OrderByClause && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}