//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class PropertyDeclaration(
    Guid id,
    Space prefix,
    Markers markers,
    IList<AttributeList> attributeLists,
    IList<J.Modifier> modifiers,
    TypeTree typeExpression,
    JRightPadded<TypeTree>? interfaceSpecifier,
    J.Identifier name,
    J.Block? accessors,
    ArrowExpressionClause? expressionBody,
    JLeftPadded<Expression>? initializer
    ) : Cs,Statement,TypedTree    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitPropertyDeclaration(this, p);
        }

        public Guid Id { get;  set; } = id;

        public PropertyDeclaration WithId(Guid newId)
        {
            return newId == Id ? this : new PropertyDeclaration(newId, Prefix, Markers, AttributeLists, Modifiers, TypeExpression, _interfaceSpecifier, Name, Accessors, ExpressionBody, _initializer);
        }
        public Space Prefix { get;  set; } = prefix;

        public PropertyDeclaration WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new PropertyDeclaration(Id, newPrefix, Markers, AttributeLists, Modifiers, TypeExpression, _interfaceSpecifier, Name, Accessors, ExpressionBody, _initializer);
        }
        public Markers Markers { get;  set; } = markers;

        public PropertyDeclaration WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new PropertyDeclaration(Id, Prefix, newMarkers, AttributeLists, Modifiers, TypeExpression, _interfaceSpecifier, Name, Accessors, ExpressionBody, _initializer);
        }
        public IList<Cs.AttributeList> AttributeLists { get;  set; } = attributeLists;

        public PropertyDeclaration WithAttributeLists(IList<Cs.AttributeList> newAttributeLists)
        {
            return newAttributeLists == AttributeLists ? this : new PropertyDeclaration(Id, Prefix, Markers, newAttributeLists, Modifiers, TypeExpression, _interfaceSpecifier, Name, Accessors, ExpressionBody, _initializer);
        }
        public IList<J.Modifier> Modifiers { get;  set; } = modifiers;

        public PropertyDeclaration WithModifiers(IList<J.Modifier> newModifiers)
        {
            return newModifiers == Modifiers ? this : new PropertyDeclaration(Id, Prefix, Markers, AttributeLists, newModifiers, TypeExpression, _interfaceSpecifier, Name, Accessors, ExpressionBody, _initializer);
        }
        public TypeTree TypeExpression { get;  set; } = typeExpression;

        public PropertyDeclaration WithTypeExpression(TypeTree newTypeExpression)
        {
            return ReferenceEquals(newTypeExpression, TypeExpression) ? this : new PropertyDeclaration(Id, Prefix, Markers, AttributeLists, Modifiers, newTypeExpression, _interfaceSpecifier, Name, Accessors, ExpressionBody, _initializer);
        }
        private JRightPadded<TypeTree>? _interfaceSpecifier = interfaceSpecifier;
        public TypeTree? InterfaceSpecifier => _interfaceSpecifier?.Element;

        public PropertyDeclaration WithInterfaceSpecifier(TypeTree? newInterfaceSpecifier)
        {
            return Padding.WithInterfaceSpecifier(JRightPadded<TypeTree>.WithElement(_interfaceSpecifier, newInterfaceSpecifier));
        }
        public J.Identifier Name { get;  set; } = name;

        public PropertyDeclaration WithName(J.Identifier newName)
        {
            return ReferenceEquals(newName, Name) ? this : new PropertyDeclaration(Id, Prefix, Markers, AttributeLists, Modifiers, TypeExpression, _interfaceSpecifier, newName, Accessors, ExpressionBody, _initializer);
        }
        public J.Block? Accessors { get;  set; } = accessors;

        public PropertyDeclaration WithAccessors(J.Block? newAccessors)
        {
            return ReferenceEquals(newAccessors, Accessors) ? this : new PropertyDeclaration(Id, Prefix, Markers, AttributeLists, Modifiers, TypeExpression, _interfaceSpecifier, Name, newAccessors, ExpressionBody, _initializer);
        }
        public Cs.ArrowExpressionClause? ExpressionBody { get;  set; } = expressionBody;

        public PropertyDeclaration WithExpressionBody(Cs.ArrowExpressionClause? newExpressionBody)
        {
            return ReferenceEquals(newExpressionBody, ExpressionBody) ? this : new PropertyDeclaration(Id, Prefix, Markers, AttributeLists, Modifiers, TypeExpression, _interfaceSpecifier, Name, Accessors, newExpressionBody, _initializer);
        }
        private JLeftPadded<Expression>? _initializer = initializer;
        public Expression? Initializer => _initializer?.Element;

        public PropertyDeclaration WithInitializer(Expression? newInitializer)
        {
            return Padding.WithInitializer(JLeftPadded<Expression>.WithElement(_initializer, newInitializer));
        }
        public sealed record PaddingHelper(Cs.PropertyDeclaration T)
        {
            public JRightPadded<TypeTree>? InterfaceSpecifier { get => T._interfaceSpecifier;  set => T._interfaceSpecifier = value; }

            public Cs.PropertyDeclaration WithInterfaceSpecifier(JRightPadded<TypeTree>? newInterfaceSpecifier)
            {
                return InterfaceSpecifier == newInterfaceSpecifier ? T : new Cs.PropertyDeclaration(T.Id, T.Prefix, T.Markers, T.AttributeLists, T.Modifiers, T.TypeExpression, newInterfaceSpecifier, T.Name, T.Accessors, T.ExpressionBody, T._initializer);
            }

            public JLeftPadded<Expression>? Initializer { get => T._initializer;  set => T._initializer = value; }

            public Cs.PropertyDeclaration WithInitializer(JLeftPadded<Expression>? newInitializer)
            {
                return Initializer == newInitializer ? T : new Cs.PropertyDeclaration(T.Id, T.Prefix, T.Markers, T.AttributeLists, T.Modifiers, T.TypeExpression, T._interfaceSpecifier, T.Name, T.Accessors, T.ExpressionBody, newInitializer);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is PropertyDeclaration && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}