//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    /// <summary>
    /// Represents a C# relational pattern that matches values using comparison operators.
    /// <br/>
    /// For example:
    /// <code>
    ///     // Simple relational patterns
    ///     if (number is &gt; 0)
    ///     if (value is &lt;= 100)
    ///     // In switch expressions
    ///     return size switch {
    ///         &gt; 100 =&gt; "Large",
    ///         &lt; 0 =&gt; "Invalid",
    ///         _ =&gt; "Normal"
    ///     };
    ///     // Combined with other patterns
    ///     if (x is &gt; 0 and &lt; 100)
    ///     // With properties
    ///     if (person is { Age: &gt;= 18 })
    /// </code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class RelationalPattern(
    Guid id,
    Space prefix,
    Markers markers,
    JLeftPadded<RelationalPattern.OperatorType> @operator,
    Expression value
    ) : Cs.Pattern, Expression<RelationalPattern>, J<RelationalPattern>, MutableTree<RelationalPattern>
    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitRelationalPattern(this, p);
        }

        public Guid Id { get;  set; } = id;

        public RelationalPattern WithId(Guid newId)
        {
            return newId == Id ? this : new RelationalPattern(newId, Prefix, Markers, _operator, Value);
        }
        public Space Prefix { get;  set; } = prefix;

        public RelationalPattern WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new RelationalPattern(Id, newPrefix, Markers, _operator, Value);
        }
        public Markers Markers { get;  set; } = markers;

        public RelationalPattern WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new RelationalPattern(Id, Prefix, newMarkers, _operator, Value);
        }
        private JLeftPadded<OperatorType> _operator = @operator;
        public OperatorType Operator => _operator.Element;

        public RelationalPattern WithOperator(OperatorType newOperator)
        {
            return Padding.WithOperator(_operator.WithElement(newOperator));
        }
        public Expression Value { get;  set; } = value;

        public RelationalPattern WithValue(Expression newValue)
        {
            return ReferenceEquals(newValue, Value) ? this : new RelationalPattern(Id, Prefix, Markers, _operator, newValue);
        }
        public enum OperatorType
        {
            LessThan,
            LessThanOrEqual,
            GreaterThan,
            GreaterThanOrEqual,
        }
        public sealed record PaddingHelper(Cs.RelationalPattern T)
        {
            public JLeftPadded<Cs.RelationalPattern.OperatorType> Operator { get => T._operator;  set => T._operator = value; }

            public Cs.RelationalPattern WithOperator(JLeftPadded<Cs.RelationalPattern.OperatorType> newOperator)
            {
                return Operator == newOperator ? T : new Cs.RelationalPattern(T.Id, T.Prefix, T.Markers, newOperator, T.Value);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is RelationalPattern && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}