//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class UsingStatement(
    Guid id,
    Space prefix,
    Markers markers,
    Keyword? awaitKeyword,
    JLeftPadded<Expression> expression,
    Statement statement
    ) : Cs,Statement    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitUsingStatement(this, p);
        }

        public Guid Id { get;  set; } = id;

        public UsingStatement WithId(Guid newId)
        {
            return newId == Id ? this : new UsingStatement(newId, Prefix, Markers, AwaitKeyword, _expression, Statement);
        }
        public Space Prefix { get;  set; } = prefix;

        public UsingStatement WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new UsingStatement(Id, newPrefix, Markers, AwaitKeyword, _expression, Statement);
        }
        public Markers Markers { get;  set; } = markers;

        public UsingStatement WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new UsingStatement(Id, Prefix, newMarkers, AwaitKeyword, _expression, Statement);
        }
        public Cs.Keyword? AwaitKeyword { get;  set; } = awaitKeyword;

        public UsingStatement WithAwaitKeyword(Cs.Keyword? newAwaitKeyword)
        {
            return ReferenceEquals(newAwaitKeyword, AwaitKeyword) ? this : new UsingStatement(Id, Prefix, Markers, newAwaitKeyword, _expression, Statement);
        }
        private JLeftPadded<Expression> _expression = expression;
        public Expression Expression => _expression.Element;

        public UsingStatement WithExpression(Expression newExpression)
        {
            return Padding.WithExpression(_expression.WithElement(newExpression));
        }
        public Statement Statement { get;  set; } = statement;

        public UsingStatement WithStatement(Statement newStatement)
        {
            return ReferenceEquals(newStatement, Statement) ? this : new UsingStatement(Id, Prefix, Markers, AwaitKeyword, _expression, newStatement);
        }
        public sealed record PaddingHelper(Cs.UsingStatement T)
        {
            public JLeftPadded<Expression> Expression { get => T._expression;  set => T._expression = value; }

            public Cs.UsingStatement WithExpression(JLeftPadded<Expression> newExpression)
            {
                return Expression == newExpression ? T : new Cs.UsingStatement(T.Id, T.Prefix, T.Markers, T.AwaitKeyword, newExpression, T.Statement);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is UsingStatement && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}