//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    /// <summary>
    /// Represents a var pattern that is used in switch statement pattern matching.
    /// <code>
    /// case var (x, y):
    ///      ^^^
    /// </code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class VarPattern(
    Guid id,
    Space prefix,
    Markers markers,
    VariableDesignation designation
    ) : Cs,Cs.Pattern    {
        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitVarPattern(this, p);
        }

        public Guid Id { get;  set; } = id;

        public VarPattern WithId(Guid newId)
        {
            return newId == Id ? this : new VarPattern(newId, Prefix, Markers, Designation);
        }
        public Space Prefix { get;  set; } = prefix;

        public VarPattern WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new VarPattern(Id, newPrefix, Markers, Designation);
        }
        public Markers Markers { get;  set; } = markers;

        public VarPattern WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new VarPattern(Id, Prefix, newMarkers, Designation);
        }
        public Cs.VariableDesignation Designation { get;  set; } = designation;

        public VarPattern WithDesignation(Cs.VariableDesignation newDesignation)
        {
            return ReferenceEquals(newDesignation, Designation) ? this : new VarPattern(Id, Prefix, Markers, newDesignation);
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is VarPattern && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}