//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    /// <summary>
    /// Represents a C# LINQ where clause that filters elements in a query based on a condition.
    /// <br/>
    /// For example:
    /// <code>
    ///     // Simple where clause
    ///     from p in people
    ///     where p.Age &gt;= 18
    ///     select p
    ///     // Multiple where clauses
    ///     from p in people
    ///     where p.Age &gt;= 18
    ///     where p.Name.StartsWith("J")
    ///     select p
    ///     // Where with complex condition
    ///     from o in orders
    ///     where o.Total &gt; 1000 && o.Status == "Pending"
    ///     select o
    /// </code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class WhereClause(
    Guid id,
    Space prefix,
    Markers markers,
    Expression condition
    ) : Cs,Cs.QueryClause    {
        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitWhereClause(this, p);
        }

        public Guid Id { get;  set; } = id;

        public WhereClause WithId(Guid newId)
        {
            return newId == Id ? this : new WhereClause(newId, Prefix, Markers, Condition);
        }
        public Space Prefix { get;  set; } = prefix;

        public WhereClause WithPrefix(Space newPrefix)
        {
            return newPrefix == Prefix ? this : new WhereClause(Id, newPrefix, Markers, Condition);
        }
        public Markers Markers { get;  set; } = markers;

        public WhereClause WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, Markers) ? this : new WhereClause(Id, Prefix, newMarkers, Condition);
        }
        public Expression Condition { get;  set; } = condition;

        public WhereClause WithCondition(Expression newCondition)
        {
            return ReferenceEquals(newCondition, Condition) ? this : new WhereClause(Id, Prefix, Markers, newCondition);
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is WhereClause && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}