//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    public partial class AssignmentOperation(
    Guid id,
    Space prefix,
    Markers markers,
    Expression variable,
    JLeftPadded<AssignmentOperation.OperatorType> @operator,
    Expression assignment,
    JavaType? type
    ) : Cs, Statement, Expression, TypedTree, MutableTree<AssignmentOperation>
    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitAssignmentOperation(this, p);
        }

        public Guid Id => id;

        public AssignmentOperation WithId(Guid newId)
        {
            return newId == id ? this : new AssignmentOperation(newId, prefix, markers, variable, _operator, assignment, type);
        }
        public Space Prefix => prefix;

        public AssignmentOperation WithPrefix(Space newPrefix)
        {
            return newPrefix == prefix ? this : new AssignmentOperation(id, newPrefix, markers, variable, _operator, assignment, type);
        }
        public Markers Markers => markers;

        public AssignmentOperation WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, markers) ? this : new AssignmentOperation(id, prefix, newMarkers, variable, _operator, assignment, type);
        }
        public Expression Variable => variable;

        public AssignmentOperation WithVariable(Expression newVariable)
        {
            return ReferenceEquals(newVariable, variable) ? this : new AssignmentOperation(id, prefix, markers, newVariable, _operator, assignment, type);
        }
        private readonly JLeftPadded<OperatorType> _operator = @operator;
        public OperatorType Operator => _operator.Element;

        public AssignmentOperation WithOperator(OperatorType newOperator)
        {
            return Padding.WithOperator(_operator.WithElement(newOperator));
        }
        public Expression Assignment => assignment;

        public AssignmentOperation WithAssignment(Expression newAssignment)
        {
            return ReferenceEquals(newAssignment, assignment) ? this : new AssignmentOperation(id, prefix, markers, variable, _operator, newAssignment, type);
        }
        public JavaType? Type => type;

        public AssignmentOperation WithType(JavaType? newType)
        {
            return newType == type ? this : new AssignmentOperation(id, prefix, markers, variable, _operator, assignment, newType);
        }
        public enum OperatorType
        {
            NullCoalescing,
        }
        public sealed record PaddingHelper(Cs.AssignmentOperation T)
        {
            public JLeftPadded<Cs.AssignmentOperation.OperatorType> Operator => T._operator;

            public Cs.AssignmentOperation WithOperator(JLeftPadded<Cs.AssignmentOperation.OperatorType> newOperator)
            {
                return T._operator == newOperator ? T : new Cs.AssignmentOperation(T.Id, T.Prefix, T.Markers, T.Variable, newOperator, T.Assignment, T.Type);
            }

        }

        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is AssignmentOperation && other.Id == Id;
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}