//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    public partial class CollectionExpression(
    Guid id,
    Space prefix,
    Markers markers,
    IList<JRightPadded<Expression>> elements,
    JavaType type
    ) : Cs, Expression, TypedTree, MutableTree<CollectionExpression>
    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitCollectionExpression(this, p);
        }

        public Guid Id => id;

        public CollectionExpression WithId(Guid newId)
        {
            return newId == id ? this : new CollectionExpression(newId, prefix, markers, _elements, type);
        }
        public Space Prefix => prefix;

        public CollectionExpression WithPrefix(Space newPrefix)
        {
            return newPrefix == prefix ? this : new CollectionExpression(id, newPrefix, markers, _elements, type);
        }
        public Markers Markers => markers;

        public CollectionExpression WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, markers) ? this : new CollectionExpression(id, prefix, newMarkers, _elements, type);
        }
        private readonly IList<JRightPadded<Expression>> _elements = elements;
        public IList<Expression> Elements => _elements.Elements();

        public CollectionExpression WithElements(IList<Expression> newElements)
        {
            return Padding.WithElements(_elements.WithElements(newElements));
        }
        public JavaType Type => type;

        public CollectionExpression WithType(JavaType newType)
        {
            return newType == type ? this : new CollectionExpression(id, prefix, markers, _elements, newType);
        }
        public sealed record PaddingHelper(Cs.CollectionExpression T)
        {
            public IList<JRightPadded<Expression>> Elements => T._elements;

            public Cs.CollectionExpression WithElements(IList<JRightPadded<Expression>> newElements)
            {
                return T._elements == newElements ? T : new Cs.CollectionExpression(T.Id, T.Prefix, T.Markers, newElements, T.Type);
            }

        }

        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is CollectionExpression && other.Id == Id;
        }

        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}