//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class DiscardVariableDesignation(
    Guid id,
    Space prefix,
    Markers markers,
    J.Identifier discard
    ) : Cs.VariableDesignation, Cs, MutableTree<DiscardVariableDesignation>
    {
        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitDiscardVariableDesignation(this, p);
        }

        public JavaType? Type => Extensions.GetJavaType(this);

        public DiscardVariableDesignation WithType(JavaType newType)
        {
            return Extensions.WithJavaType(this, newType);
        }
        public Guid Id => id;

        public DiscardVariableDesignation WithId(Guid newId)
        {
            return newId == id ? this : new DiscardVariableDesignation(newId, prefix, markers, discard);
        }
        public Space Prefix => prefix;

        public DiscardVariableDesignation WithPrefix(Space newPrefix)
        {
            return newPrefix == prefix ? this : new DiscardVariableDesignation(id, newPrefix, markers, discard);
        }
        public Markers Markers => markers;

        public DiscardVariableDesignation WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, markers) ? this : new DiscardVariableDesignation(id, prefix, newMarkers, discard);
        }
        public J.Identifier Discard => discard;

        public DiscardVariableDesignation WithDiscard(J.Identifier newDiscard)
        {
            return ReferenceEquals(newDiscard, discard) ? this : new DiscardVariableDesignation(id, prefix, markers, newDiscard);
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is DiscardVariableDesignation && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}