//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    /// <summary>
    /// Represents a property pattern clause in C# pattern matching, which matches against object properties.
    /// <br/>
    /// For example:
    /// <code>
    ///     // Simple property pattern
    ///     if (obj is { Name: "test" })
    ///     // Multiple properties
    ///     if (person is { Name: "John", Age: &gt; 18 })
    ///     // Nested property patterns
    ///     if (order is { Customer: { Name: "test" } })
    ///     // With variable declarations
    ///     if (person is { Id: int id, Name: string name })
    ///     // In switch expressions
    ///     return shape switch {
    ///         { Type: "circle", Radius: var r } =&gt; Math.PI * r * r,
    ///         { Type: "square", Side: var s } =&gt; s * s,
    ///         _ =&gt; 0
    ///     };
    /// </code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class PropertyPatternClause(
    Guid id,
    Space prefix,
    Markers markers,
    JContainer<Subpattern> subpatterns
    ) : Cs, MutableTree<PropertyPatternClause>
    {
        [NonSerialized] private WeakReference<PaddingHelper>? _padding;

        public PaddingHelper Padding
        {
            get
            {
                PaddingHelper? p;
                if (_padding == null)
                {
                    p = new PaddingHelper(this);
                    _padding = new WeakReference<PaddingHelper>(p);
                }
                else
                {
                    _padding.TryGetTarget(out p);
                    if (p == null || p.T != this)
                    {
                        p = new PaddingHelper(this);
                        _padding.SetTarget(p);
                    }
                }
                return p;
            }
        }

        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitPropertyPatternClause(this, p);
        }

        public Guid Id => id;

        public PropertyPatternClause WithId(Guid newId)
        {
            return newId == id ? this : new PropertyPatternClause(newId, prefix, markers, _subpatterns);
        }
        public Space Prefix => prefix;

        public PropertyPatternClause WithPrefix(Space newPrefix)
        {
            return newPrefix == prefix ? this : new PropertyPatternClause(id, newPrefix, markers, _subpatterns);
        }
        public Markers Markers => markers;

        public PropertyPatternClause WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, markers) ? this : new PropertyPatternClause(id, prefix, newMarkers, _subpatterns);
        }
        private readonly JContainer<Cs.Subpattern> _subpatterns = subpatterns;
        public IList<Cs.Subpattern> Subpatterns => _subpatterns.GetElements();

        public PropertyPatternClause WithSubpatterns(IList<Cs.Subpattern> newSubpatterns)
        {
            return Padding.WithSubpatterns(JContainer<Cs.Subpattern>.WithElements(_subpatterns, newSubpatterns));
        }
        public sealed record PaddingHelper(Cs.PropertyPatternClause T)
        {
            public JContainer<Cs.Subpattern> Subpatterns => T._subpatterns;

            public Cs.PropertyPatternClause WithSubpatterns(JContainer<Cs.Subpattern> newSubpatterns)
            {
                return T._subpatterns == newSubpatterns ? T : new Cs.PropertyPatternClause(T.Id, T.Prefix, T.Markers, newSubpatterns);
            }

        }

        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is PropertyPatternClause && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}