//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class SingleVariableDesignation(
    Guid id,
    Space prefix,
    Markers markers,
    J.Identifier name
    ) : Cs.VariableDesignation, Cs, MutableTree<SingleVariableDesignation>
    {
        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitSingleVariableDesignation(this, p);
        }

        public JavaType? Type => Extensions.GetJavaType(this);

        public SingleVariableDesignation WithType(JavaType newType)
        {
            return Extensions.WithJavaType(this, newType);
        }
        public Guid Id => id;

        public SingleVariableDesignation WithId(Guid newId)
        {
            return newId == id ? this : new SingleVariableDesignation(newId, prefix, markers, name);
        }
        public Space Prefix => prefix;

        public SingleVariableDesignation WithPrefix(Space newPrefix)
        {
            return newPrefix == prefix ? this : new SingleVariableDesignation(id, newPrefix, markers, name);
        }
        public Markers Markers => markers;

        public SingleVariableDesignation WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, markers) ? this : new SingleVariableDesignation(id, prefix, newMarkers, name);
        }
        public J.Identifier Name => name;

        public SingleVariableDesignation WithName(J.Identifier newName)
        {
            return ReferenceEquals(newName, name) ? this : new SingleVariableDesignation(id, prefix, markers, newName);
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is SingleVariableDesignation && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}