//------------------------------------------------------------------------------
// <auto-generated>
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
#nullable enable
#pragma warning disable CS0108 // 'member1' hides inherited member 'member2'. Use the new keyword if hiding was intended.
#pragma warning disable CS8767 // Nullability of reference types in type of parameter doesn't match implicitly implemented member (possibly because of nullability attributes).
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using Rewrite.Core;
using Rewrite.Core.Marker;
using FileAttributes = Rewrite.Core.FileAttributes;
using Rewrite.RewriteJava.Tree;

namespace Rewrite.RewriteCSharp.Tree;

[SuppressMessage("ReSharper", "InconsistentNaming")]
[SuppressMessage("ReSharper", "PossibleUnintendedReferenceComparison")]
[SuppressMessage("ReSharper", "InvertIf")]
[SuppressMessage("ReSharper", "RedundantExtendsListEntry")]
[SuppressMessage("ReSharper", "UnusedMember.Global")]
[SuppressMessage("ReSharper", "RedundantNameQualifier")]
public partial interface Cs : J
{
    /// <summary>
    /// Represents a C# type pattern, which matches a value against a type and optionally assigns it to a new variable.
    /// <br/>
    /// For example:
    /// <code>
    ///     // Simple type pattern
    ///     if (obj is string)
    ///     // Type pattern with variable declaration
    ///     if (obj is string str)
    ///     // Type pattern with array type
    ///     if (obj is int[])
    ///     // Type pattern with generic type
    ///     if (obj is List&lt;string&gt; stringList)
    ///     // Type pattern with nullable type
    ///     if (obj is string? nullableStr)
    ///     // Switch expression with type pattern
    ///     object value = someValue switch {
    ///         string s =&gt; s.Length,
    ///         int n =&gt; n * 2,
    ///         _ =&gt; 0
    ///     };
    /// </code>
    /// </summary>
    #if DEBUG_VISITOR
    [DebuggerStepThrough]
    #endif
    public partial class TypePattern(
    Guid id,
    Space prefix,
    Markers markers,
    TypeTree typeIdentifier,
    VariableDesignation? designation
    ) : Cs.Pattern, Expression<TypePattern>, J<TypePattern>, MutableTree<TypePattern>
    {
        public J? AcceptCSharp<P>(CSharpVisitor<P> v, P p)
        {
            return v.VisitTypePattern(this, p);
        }

        public Guid Id => id;

        public TypePattern WithId(Guid newId)
        {
            return newId == id ? this : new TypePattern(newId, prefix, markers, typeIdentifier, designation);
        }
        public Space Prefix => prefix;

        public TypePattern WithPrefix(Space newPrefix)
        {
            return newPrefix == prefix ? this : new TypePattern(id, newPrefix, markers, typeIdentifier, designation);
        }
        public Markers Markers => markers;

        public TypePattern WithMarkers(Markers newMarkers)
        {
            return ReferenceEquals(newMarkers, markers) ? this : new TypePattern(id, prefix, newMarkers, typeIdentifier, designation);
        }
        public TypeTree TypeIdentifier => typeIdentifier;

        public TypePattern WithTypeIdentifier(TypeTree newTypeIdentifier)
        {
            return ReferenceEquals(newTypeIdentifier, typeIdentifier) ? this : new TypePattern(id, prefix, markers, newTypeIdentifier, designation);
        }
        public Cs.VariableDesignation? Designation => designation;

        public TypePattern WithDesignation(Cs.VariableDesignation? newDesignation)
        {
            return ReferenceEquals(newDesignation, designation) ? this : new TypePattern(id, prefix, markers, typeIdentifier, newDesignation);
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public bool Equals(Rewrite.Core.Tree? other)
        {
            return other is TypePattern && other.Id == Id;
        }
        #if DEBUG_VISITOR
        [DebuggerStepThrough]
        #endif
        public override int GetHashCode()
        {
            return Id.GetHashCode();
        }
    }
}